# Generated by Django 3.2.5 on 2021-07-28 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_lesson_module'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='module_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modules', to='course.module'),
        ),
    ]
