# Generated by Django 3.2.5 on 2021-07-29 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_alter_lesson_module_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='module_name',
        ),
        migrations.AddField(
            model_name='module',
            name='lesson_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lessons', to='course.lesson'),
        ),
    ]
