# Generated by Django 3.2.5 on 2021-07-29 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_auto_20210729_1201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='lesson_name',
        ),
        migrations.AddField(
            model_name='module',
            name='lesson',
            field=models.ManyToManyField(to='course.Lesson'),
        ),
    ]
