# Generated by Django 3.2.5 on 2021-07-29 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_auto_20210729_1230'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='lesson',
        ),
        migrations.AddField(
            model_name='module',
            name='lessons',
            field=models.ManyToManyField(blank=True, to='course.Lesson'),
        ),
    ]
