# Generated by Django 3.2.5 on 2021-07-29 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_auto_20210729_1244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='module_name',
        ),
        migrations.AddField(
            model_name='course',
            name='module_name',
            field=models.ManyToManyField(blank=True, to='course.Module'),
        ),
    ]
