# Generated by Django 3.2.5 on 2021-07-29 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0008_auto_20210729_1256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='module_name',
        ),
        migrations.RemoveField(
            model_name='module',
            name='lessons',
        ),
        migrations.AddField(
            model_name='lesson',
            name='module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='module', to='course.module'),
        ),
        migrations.AddField(
            model_name='module',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course', to='course.course'),
        ),
    ]
