# Generated by Django 3.2.5 on 2021-08-16 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0011_auto_20210803_0906'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='max_people',
        ),
        migrations.RemoveField(
            model_name='course',
            name='min_people',
        ),
    ]
