# Generated by Django 3.2.5 on 2021-11-16 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
        ('coaches', '0001_initial'),
        ('members', '0003_alter_booking_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='coach_name',
            field=models.ForeignKey(limit_choices_to={'status': '1'}, on_delete=django.db.models.deletion.CASCADE, to='coaches.coach'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='course_name',
            field=models.ForeignKey(limit_choices_to={'status': '1'}, on_delete=django.db.models.deletion.CASCADE, to='course.course'),
        ),
    ]
